### PR TITLE
Use Pyrodigal as a faster and maintained Prodigal alternative

### PR DESCRIPTION
**Pull request by oschwengers**
Since release [2.0.0](https://github.com/althonos/pyrodigal/releases/tag/v2.0.0) [Pyrodigal](https://github.com/althonos/pyrodigal) is a reliable, faster and most important actively maintained version of or successor to Prodigal.

Due to @jhahnfeld 's [comparison](https://github.com/jhahnfeld/prodigal-pyrodigal-comparison) (Kudos!) we're confident enough to replace the tested and well-accepted Prodigal by Pyrodigal.

Further information:
- Backward compatibility of Prodigal training files should be given
- Slightly shorter overall runtimes due to parallel Python in-memory gene predictions in contrast to Prodigal as an external process

### CODE REVIEW

**Comment by flass** [comment]
Hi @oschwengers ,

thanks a lot for integrating Pyrodigal into Bakta (and for developing the whole thing - it's great!) 
quick questions:
- would you say that the code was stable at the stage where you merged the Pyrodigal branch into main 0606683 ?
- if so, would it be possible to push a minor release that integrates this fix/upgrade? 

just a bit of context:
I (and my institute) have a big project of annotating lots (LOTS) of genomes and we would like to do it with a Pyrodigal-suported version but we also want to make sure that it is fairly stable version; at the moment, i'm not too sure which commit to settle on for this, so I was hoping maybe you could release a minor version (that'd be `v1.5.2` I presume) sometime soon? either directly tag 0606683 or a later commit you're confident is fairly stable?

Many thanks,

Florent

**Comment by oschwengers** [comment]
Thanks @flass for reaching out and considering Bakta for this large-scale analysis!

Yes, I'd say it has been considered as stabel at https://github.com/oschwengers/bakta/commit/93c842b73a7b177b60bce456cb4ed1a59abd62fa

And yes, I could easily release a `1.5.2` version - I totally see your point and we're in a fairly equal situation ourselves. However, as I'm almost done with the upcoming `1.6.0`, I'd rather skip 1.5.2 and release 1.6.0 hopefully next week. Would that be OK for you?

**Comment by flass** [comment]
Hey - thanks for coming back to me that quickly! this sounds great :-) 
I totally get it, if you're going to have `1.6.0` ready that soon, we might as well wait for it. if my colleagues get really impatient, i'll use the code from 93c842b.
thank you again for your help and awesome work!
Bes wishes,
Florent

**Comment by oschwengers** [comment]
@flass FYI, [v1.6.0](https://github.com/oschwengers/bakta/releases/tag/v1.6.0) is now out ;-)

**Comment by flass** [comment]
awesome news! thanks a lot @oschwengers :-)

**Pull request merged**
