### PR TITLE
add link to the Galaxy bakta tool

### PR DESCRIPTION
**Pull request by bgruening**
Great tool! :)

### CODE REVIEW

**Comment by oschwengers** [comment]
Thanks Björn (@bgruening),
I didn't recognize that it's already available on Galaxy. Is it fully functional including the database?

**Comment by oschwengers** [comment]
@bgruening,
thanks for reporting. I just saw that the database is not yet available. It says "no option available". Is there anything I could potentially help with?

**Comment by oschwengers** [comment]
FYI: @pimarin is working on that: https://github.com/galaxyproject/tools-iuc/pull/4723

I'll merge this as soon as the the data manager is ready and the database available on Galaxy.

**Comment by pimarin** [comment]
It still running to fix bug in the data manager to allow a complete tool on Galaxy 
I hope to finish this week !

**Comment by bgruening** [comment]
Upps sorry didn't came back here. The tool should work, I just tested itz the database is installed. I will try help with the DM when I'm back from vacation but the link should work imho.

Thanks @pimarin @oschwengers  for all the work!

**Comment by oschwengers** [comment]
Hey Björn, 
sorry for not merging this for such a long time. I was a bit reluctant to add single platform badges. Now, that Bakta is available via various packaging frameworks and on different platforms,  I added a custom Usegalaxy.eu badge next to some others. With that, I'll finally close this.

Thanks again

**Pull request closed without merging**
